### ISSUE TITLE
_updateOptions is non functional

### ISSUE THREAD

**Issue by alaendle** [timdeputter/purescript-apexcharts#10]
Please note that both `_updateOptions`
https://github.com/timdeputter/purescript-apexcharts/blob/dbb567a0d5ef534b6d1df4bad22273dfb438f3c5/src/Apexcharts.purs#L30
and `render`
https://github.com/timdeputter/purescript-apexcharts/blob/dbb567a0d5ef534b6d1df4bad22273dfb438f3c5/src/Apexcharts.purs#L28
use the `ApexCharts` type as an argument. However, `ApexCharts` represents the definition, not the chart itself. While `render`for sure recognizes this fact, `_updateOptions` tries to interpret the definition as the actual chart.
https://github.com/timdeputter/purescript-apexcharts/blob/dbb567a0d5ef534b6d1df4bad22273dfb438f3c5/src/Apexcharts.js#L13-L24
I tried to fix this, but as it seems to be necessary to lazily initialize the chart, it is not super easy to transfer the chart instance to the update-method. So a super ugly fix (without the need to change the API) might (mis-)use the chart-id - but I'm pretty sure there are better ways to fix this for JS-experts 😉 

```
exports._updateOptions = function(chartDef) {
    return function(newOptions) {
        return function() {
            var parent;
            if (chartDef.el) {
                parent = chartDef.el;
            } else {
                parent = document.querySelector(chartDef.selector);
            }
            var chartId = parent.firstElementChild.id.replace('apexcharts', '');
    
            ApexCharts.exec(chartId, 'updateOptions', newOptions);
        };
    };
};
```

**Comment by timdeputter** [comment]
> 
> 
> Please note that both `_updateOptions`
> 
> https://github.com/timdeputter/purescript-apexcharts/blob/dbb567a0d5ef534b6d1df4bad22273dfb438f3c5/src/Apexcharts.purs#L30
> 
> and `render`
> 
> https://github.com/timdeputter/purescript-apexcharts/blob/dbb567a0d5ef534b6d1df4bad22273dfb438f3c5/src/Apexcharts.purs#L28
> 
> use the `ApexCharts` type as an argument. However, `ApexCharts` represents the definition, not the chart itself. While `render`for sure recognizes this fact, `_updateOptions` tries to interpret the definition as the actual chart.
> 
> https://github.com/timdeputter/purescript-apexcharts/blob/dbb567a0d5ef534b6d1df4bad22273dfb438f3c5/src/Apexcharts.js#L13-L24
> 

This definitly shows that I never really tested this feature :woozy_face:

> I tried to fix this, but as it seems to be necessary to lazily initialize the chart, it is not super easy to transfer the chart instance to the update-method. So a super ugly fix (without the need to change the API) might (mis-)use the chart-id - but I'm pretty sure there are better ways to fix this for JS-experts 😉
> 
> ```
> exports._updateOptions = function(chartDef) {
>     return function(newOptions) {
>         return function() {
>             var parent;
>             if (chartDef.el) {
>                 parent = chartDef.el;
>             } else {
>                 parent = document.querySelector(chartDef.selector);
>             }
>             var chartId = parent.firstElementChild.id.replace('apexcharts', '');
>     
>             ApexCharts.exec(chartId, 'updateOptions', newOptions);
>         };
>     };
> };
> ```

Another possible fix would be to pass the chartId as String and then use it directly:
```
exports._updateOptions = function(chartId) {
    return function(newOptions) {
        return function() {    
            ApexCharts.exec(chartId, 'updateOptions', newOptions);
        };
    };
};
```

**Comment by timdeputter** [comment]
@gbagan, thank you for that PR. Looks like a good solution. 

Not sure how (if at all) the API is used. If somebody is depending on it, please comment. Otherwise, I am happy to merge.
