### ISSUE TITLE
fontFamily from `Apexcharts.Xaxis.Labels.Style` is not working

### ISSUE THREAD

**Issue by ongyiren1994** [timdeputter/purescript-apexcharts#2]
The function `fontFamily` from `Apexcharts.Xaxis.Labels.Style` is not working as expected. However, the one from `Apexcharts.Yaxis.Labels.Style` works.

**Comment by timdeputter** [comment]
The option should work as documented in the apexcharts docs here: https://apexcharts.com/docs/options/xaxis/

Maybe it’s an issue with apexcharts.js itself. Did you try it out in js?
