### ISSUE TITLE
Compatibility with recent Purescript version

### ISSUE THREAD

**Issue by Swordlash** [timdeputter/purescript-apexcharts#7]
Hi,
is this library still maintained? Are there plans to make it compile on latest purescript version?

**Comment by timdeputter** [comment]
Hi, thanks for your feedback.

Cause this project is just a sideproject of mine, it is not regulary maintained. I didn't check it for the current purescript version and I don't think I will have time to do anytime soon. Maybe you could describe what problems you did run into or, if you want to, you are welcome to provide a pullrequest. 

Kind regards
Tim

**Comment by Swordlash** [comment]
Only outdated versions of packages. I run `spago init` on the package to force most recent versions and it compiles with the most recent package set. The only thing I had to do was to change monad in `test/Main` from `Effect` to `Aff`, so one-liner in code.
